# [ヘリコバクター学会発表原稿](http://winterwang.github.io/metronidazole/#1)

6月24日（金）14:50-16:20 第一会場 (1F フィルハーモニアホール)

若年者除菌と胃がん予防：　司会：菊地正悟　奥田真珠美


## Slide 1; time: 0s logo only.

## Slide 2; Title;  time: 10s

愛知医大公衆衛生の王と申します．本日は，メトロニダゾールの副作用や発がん性などの安全性について発表いたします．
どうぞよろしくお願いいたします．


## Slide 3; Background; time: 40s 

現在，メトロニダゾールは世界中に幅広くピロリ菌の抗菌薬として処方されています．日本の場合，成人の二次除菌でもよく使われている薬であり，保険の適用もできます．

これは未公表のデータですが，日本の中高生においてPPI+amoxicillin+クラリスロマイシン併用療法の除菌率は60.5％に対して，PPI+amoxicillin+メトロニダゾール併用療法の除菌成功率が98.3%，有意に高い成功率でした．

また，近年の報告によりますと，日本の小児における，クラリスロマイシンの耐性率はすでに40%を超えました．

しかしながら，国際がん研究機関によりますと，メトロニダゾールの発がん性リスクがグループ2Bに分類されています．つまり，ヒトに対する発癌性が疑われると指摘されています．

## Slide 4; time:20s

今回は，今までにパブリッシュされたメトロニダゾールの使用に関する副作用や安全性の関連報告を簡単にレビューした結果を報告いたします．

Pubmedで使われた検索用語はこちらになります．


## Slide 5; time: 1min　（実験中の投与量を確認する）

検索で出てきましたエビデンスは，こちらの一覧表で見てみましょう．

発がん性について報告により，マウスの肺がん，肝がん，リンパ腫，乳がん，と下垂体「かすいたい」がんの発生リスクが有意に上昇しましたが，いずれの報告も1990年代前の研究報告でした．これらの結果を踏まえて，国際がん研究機関がメトロニダゾールの発がん性を2Bに分類したと考えられます．

また，遺伝子損傷に関する報告からはnegative, 生殖器や生殖能力の低下が報告されています．

## Slide 6; time: 2s 

しかし，人を対象とした研究から，メトロニダゾールの使用はがん発生リスクを上げるという報告はまだありません．


## Slide 7; time: 10s 
例えば，先ほどのマウス実験と同じ時代にNew England Journal of Medicineで公表した論文では，771名メトロニダゾール使用した女性の観察研究では，がんリスクの上昇は認められませんでした．

## Slide 8; time: 40s 
その後，メトロニダゾールの発がん性に関する研究は，十分ではありません．

1980年代と1990年代に実施されたヒトでの観察研究からは，いずれも，がんの発生と関連がないという結果でした．

特に，約5,000人のメトロニダゾール使用者と非使用者を性別と年齢を１対１マッチさせた対照研究を12年間に渡って追跡した結果，使用者のがん罹患リスクは非使用者とは同じ程度でした．

また，妊娠中の投与と子供のがん発生リスクとの関連を観察した研究もあり，おおよそ32万人を観察した結果がんリスクの増加はありませんでした．


## Slide 9; time: 1min 
ほかの副作用に関する結果はこちらです．

例えば長期間の使用により，癲癇（てんかん）や痙攣（けいれん），髄膜炎，脳障害など脳・神経系の症状や障害．

または大量の使用により発生した下痢（げり），吐き気（はきけ），嘔吐（おうと）など消化器系の症状．

それから，皮疹（ひしん）の皮膚症状及び膵炎の報告もありました．

そのほか薬物との相互作用と注意点については，ワーファリンの抗凝固（こうぎょうこ）作用の増強がよく知られています．また，アルコール代謝に関わるALDHの活性を阻害するため，メトロニダゾール使用中にアルコールの摂取は控える必要があります．


## Slide 10; time 15s 
では，実際外国の小児除菌ガイドラインにおいて，メトロニダゾールの使用はどのように書かれていますでしょうか．

こちらは，現在イギリスの小児除菌推奨レジメです．メトロニダゾールとクラリスロマイシン及びアモキシシリンは同時にリストされています．年齢により用量の違いと薬の組み合わせが書かれております．


## Slide 11; time 20s 
また，2011年に北米とユーロッパの関連学会が発表したエビデンスに基づく小児ガイドラインでの推奨アルゴリズムによると，投薬する前にはクラリスロマイシンの耐性が20％より高い地域では，まずクラリスロマイシンの感受性試験を行い，その結果によってクラリスロマイシンとメトロニダゾールのどちらを投与することを決めます．つまり，どちらでも，first-line therapyとして推奨されています．

`カナダの研究グループが出したコメントとしては，メトロニダゾールは変な不愉快な味がするため，コンプライアンスの低下に繋がる可能性があります．`

## Slide 12; time 10s 

結論です．短期間のメトロニダゾール使用はヒトでのがんの発生リスクの上昇は認められませんでした．  
最後に，日本の中高生におけるクラリスロマイシンの耐性が高いので，薬剤感受性を行わない場合，メトロニダゾールを含む併用療法は一つの選択肢となるうると考えられます．

以上で発表を終わります．ご清聴ありがとうございました．
